version: "3.8"

services:
  app:
    image: python:3.8.10
    command: sh -c "pip install -r requirements.txt && python app.py"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://postgres:example@postgresql:5432/bikeapp
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: bikeapp
    volumes:
      - ./db/bikeapp.sql:/docker-entrypoint-initdb.d/create_tables.sql